### ISSUE TITLE
Change license of the library to LGPLv3.

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#133]
I think LGPLv3 is a good trade-off. This will apply for the core library opening_hours.js for all further versions. The BSD license will thus not apply to newer versions of the lib, but the copyright note needs to stay.
Most scripts in this repository are already licensed under AGPLv3. This is still open for discussion. Related to https://github.com/PanierAvide/panieravide.github.io/issues/2#issuecomment-133682851
@AMDmi3, do you want to comment on this?
@amenk, you use this lib commercially? Do you expect problems with this change?

https://stackoverflow.com/questions/2015805/how-can-i-legally-use-lgpl-javascript-in-a-commercial-web-site

- [x] You mention that it is licensed under the LGPL, with reference to the full license.
- [x] That you distribute the code, and any changes to it, under the terms of the LGPL. You must release the source code in it's preferred form (not minified or obfuscated), including any changes that you make to it.
- [x] That it is dynamically linked in to your application in such a way that the user can replace it with their own version if they want.

**Comment by AMDmi3** [comment]
I don't have any problems with this.

**Comment by ypid** [comment]
@AMDmi3 Thanks for your comment and that you are ok with this.

**Comment by amenk** [comment]
From Stackoverflow:
> To comply with (3) in JavaScript, as long as you keep the code in a separate script file, and don't 
> merge it into one file with your code, you should be fine. Anyone who wants to replace it could use
> Greasemonkey or UserJS to do so.

Actually I do merge & minify the code... But all my changes were only pushed to GitHub...

**Comment by ypid** [comment]
License issues [all over the place](https://github.com/debops/ansible-cryptsetup/pull/1) :wink: 

OK, interesting. But I think minifying is still ok. When users want to replace it with there own copy they can just load there copy after your minified version has been loaded and it will overwrite it. I don’t indent to restrict you in this regard.

**Comment by ypid** [comment]
[Done](https://github.com/opening-hours/opening_hours.js/commit/6eedd993f20495fa751ea7e8ea2c5e8e65151dbe). But note that I am not a lawyer :wink:. @AMDmi3 Are you OK with the way I handled the license change?

Further refs:
* https://opensource.stackexchange.com/questions/304/can-i-take-bsd-licensed-code-and-distribute-it-under-gpl
* https://stackoverflow.com/questions/4035702/can-i-relicense-someones-mit-code-under-gpl

**Comment by AMDmi3** [comment]
Since the original license requests to retain copyright notice I think it's probably more correct to leave it be and LGPL text above BSD in both COPYING and the source.

**Comment by ypid** [comment]
You are right. Sorry that I missed that. Thanks. Still waiting for @amenk approval for closing this properly.

**Comment by AMDmi3** [comment]
Yep, this looks good. But similar change probably needed for the script.

**Comment by amenk** [comment]
I am okay with it

**Comment by ypid** [comment]
@AMDmi3 It might be difficult to specify in the library that only certain parts are under BSD while the lib as a whole is licensed under the LGPL. How should I do it?

@amenk Thanks

**Comment by AMDmi3** [comment]
> It might be difficult to specify in the library that only certain parts are under BSD while the lib as a whole is licensed under the LGPL. How should I do it?

There's no "parts". There's old and new licenses for the whole thing, you should do the same as with LICENSE file, specify new license (e.g.  short and the old one below it.

Also, I've just noticed that you also need to update license badge in README.

**Comment by ypid** [comment]
Thanks for the help. I updated the library file.

> Also, I've just noticed that you also need to update license badge in README.

Thanks for the hint but that badge will be automatically updated when I release the LGPL licensed thing via NPM :wink:

**Comment by AMDmi3** [comment]
Ok, thank you!

**Comment by ypid** [comment]
Thank you for help and for supporting me in this license change (as a FreeBSD user) :wink:

**Comment by AMDmi3** [comment]
Technically, you haven't needed my support on this as BSD license allows relicensing under (L)GPL and that is enough. Generally I stick to copyleft for end-user projects and for permissive licenses for libraries and other building blocks, but I still lean more to copyleft camp and this is more your code than mine now anyway, so I'm perfectly fine with it. It's unexpected though as I witness more projects change license from copyleft to permissive instead.

**Comment by ypid** [comment]
Sure, but as you made this library possible I wanted to hear what you think before making the switch for all further contributions.
