### ISSUE TITLE
tool proposes single digit monthdays (Apr 01->Apr 1)

### ISSUE THREAD

**Issue by aceman444** [opening-hours/opening_hours.js#139]
Hi, the tool proposes to change the syntax:
Apr 01-Nov 16 Tu-Su 10:00-18:00; Nov 17-Mar 31 Tu-Su 09:00-17:00; Mo off
to
Apr 1-Nov 16 Tu-Su 10:00-18:00; Nov 17-Mar 31 Tu-Su 09:00-17:00; Mo off

i.e. single digit day of month. But the OSM wiki states monthdays are always double digit.

**Comment by ypid** [comment]
Thanks :+1:  Fixed.

**Comment by aceman444** [comment]
Great, thanks!
