### ISSUE TITLE
detect language before translating

### ISSUE THREAD

**Issue by matkoniecz** [opening-hours/opening_hours.js#14]
For example "Pon-Cz 12:00-22:00;Pt-So 12:00-13:00;N 12:00-22:00" is relatively easy detectable as Polish rather than German, but currently "so" is changed because it fits German shortcut.

Upgrade of #10

**Comment by ypid** [comment]
Appears like this feature has been requested a second time without me setting the second issue fast enough to duplicate and closing it. As there is more discussion already in #107 about how to implement this, I am closing this issue.
