### ISSUE TITLE
Is the creation of opening_hours object expensive?

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#140]
I have a list of about 100 entries with opening times in string format. I wonder, if for display reasons I should convert all of those to `opening_times` objects before displaying them? What's the memory impact of `opening_hours` objects on simple opening times for 6 days a week?

**Comment by ypid** [comment]
Starting node uses 13696 KiB. (`ps aux --sort -rss | grep --extended-regexp '(node|USER)'`)

Loading the library uses 21492 KiB. (`var oh = require('./opening_hours');`)

Creating 100 oh objects uses 27996 KiB (`e = []; for (var i = 1; i <= 100; i++) { e.push(new oh('Mo-Fr 08:00-16:00; We off')); }`)

Not really noticeable I would say.

This is more a question than an issue. Did you try this benchmark yourself?

**Comment by pke** [comment]
No I have not yet perf tested that, it was more a general question (and yes, not an issue at all).
Since my app uses reactjs, rerendering is heavily optimized already so I was concerned about memory consumption. I think I'll go with creating `opening_hours` on demand and see if I hit any issues and come back here then.
