### ISSUE TITLE
Is there a way to attach additional information to each opening fragment?

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#141]
To save the entry fee for a venue I'd like to attach the pricing information to the opening times.
So for instance:
Mo-Fr 22:00 - 07:00 it costs 1€
Sa 20:30 - 07:00 it costs 4€

Does the lib support such addition info?

**Comment by ypid** [comment]
@pke You can use comments for this because such a feature is not yet specified. If you want to specify it, have a look at: https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours#women.2Fmen-only_days
Cheers.

**Comment by ypid** [comment]
@pke BTW. Note that there are tags for adding the fee amount: https://wiki.openstreetmap.org/wiki/Key:charge
E.g. you should not add the fee to the opening_hours tag unless you have a pretty good reason to do so.
