### ISSUE TITLE
josm validator: last value+semicolon+empty space fixes only empty space (in first run)

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#142]
input: 7-18;[empty space]
automagic correction deletes (in first run) only the space not the rest of value

second run fixes the rest

Bug or feature?

Wenn ich ein tagging habe a la: 7-18semikolon[leerzeichen] dann korrigiert Josm beim ersten Klick auf korrigieren nur das Leerzeichen. Josm- oder OH.js-Problem? Ist das so gewollt?

**Comment by ypid** [comment]
"Problem" is known. I wrote about this in the docs. I agree that this should be fixed to make usage of the library easier.

**Comment by ypid** [comment]
Seems I have fixed this issue in the mean time. "Mo: 7-18; " is prettified to "Mo 07:00-18:00". Please always include a permalink with working example to reproduce the issue. Can you confirm this?

**Comment by dex2000** [comment]
cannot directly confirm, but seen this problem long time not.
