### ISSUE TITLE
Allow overwriting Country code missing

### ISSUE THREAD

**Issue by HolgerJeromin** [opening-hours/opening_hours.js#153]
Usage scenario:
I am on mobile and want to add opening hours to a poi with vespucci. I cut the string from the poi  website and paste it into the evaluation tool. 
But instead of being able to optimize the string I only get the text:

> Country code missing which is needed to select the correct holidays (see README how to provide it). 

I not care about the correct holiday display but wanted to get a better string. 
And even when I would care: where is the Readme?

Imo the country code error should be at least a small info without breaking the functionality of the website.

**Comment by ypid** [comment]
That is a hint that your browser could not connect to [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) which is needed to do the reverse geocoding. Did you check that?

I agree that it should be possible to use the evaluation tool without an answer from Nominatim.

> And even when I would care: where is the Readme?

That is the [huge thing](https://github.com/opening-hours/opening_hours.js/blob/master/README.md) in the repository on GitHub to which the evaluation tool links.

**Comment by HolgerJeromin** [comment]
I allowed location api in the browser. The location coordinate  is filled in. But the page is still not working. I have no clue how to solve that. 

The thing with the Readme was not clear from me. Sorry. 
I know which Readme you probably meant, but this is not linked and not obvious. 
At least for a casual user. 
And after reading the Readme I still have no clue how  the text  should help me with my problem.

**Comment by ypid** [comment]
The problem should be fixed. I added a fallback and a user alert in case the query fails. You are right that things like the README mentioned in the error message should be a hyperlink. I hesitated with doing that before because not all applications which use this library can be expected to understand this. I am tracking progress of this feature request in #156.

I deployed the updated version online. Can you try it? Feel free to give feedback and/or close the issue if I fixed it :wink:

**Comment by HolgerJeromin** [comment]
Thank you very much for your fix! Works now perfectly in opera mobile :-)

**Comment by ypid** [comment]
You are welcome. Do you get the user hint that Nominatim could not be queried?

**Comment by HolgerJeromin** [comment]
yes i did.
