### ISSUE TITLE
add possibility to (simple) exclude date from permalink

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#157]
at the moment, the permalink adds the time given in time-field (actually or edited).
Would be nice, to exclude it via "copy link" withouth searching (and deleting) the date-string in URL or something similar.

Das is für mich auf englisch bisschen komplizierter zu erklren, verschiedene Herangehensweisen:
1. das JS schaut, ob das angegebene Datum sehr nah am aktuellen Datum ist und lässt das DATE einfach weg.
2. das JS baut 2 permalinks, eins mit angegebenem Datum/Zeit, eins "global" also ohne.
3. die URL lesbarer gestalten, so dass es einem Laien ins Auge fällt 
4. Bei "Datum und Zeit" einen Button, der aktuelle Zeit einfügt
5. per referer (unsicher) oder anderweitig prüfen, ob der Link direkt aufgerufen oder eingegeben wurde und einen dezenten Hinweis einblenden ("Dies ist nicht die aktuelle Zeit, bla bla") 
6. -60. [andere Ideen hier einsetzen]

Ich persönlich fände eine Kombi aus 1,4 und 5 ganz gut (Wobei 3. auch noch so ne Baustelle is imho :))

Example:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%2CWe%2CTh%2008%3A00-12%3A00%20open%2C%20Mo%2CWe%2CTh%2013%3A30-15%3A00%20open%20%22Diabetologie%22%2C%20Mo%2CWe%2CTh%2016%3A00-18%3A00%20open%20%22Allgemeinmedizin%22%3B%20Tu%2008%3A00-12%3A00%20open%20%22Allgemeinmedizin%22%2C%20Tu%2013%3A00-16%3A00%20open%20%22Diabetologie%22%2C%20Tu%2016%3A00-18%3A00%20open%3B%20Fr%2008%3A00-12%3A00%3B%20PH%20off&DATE=917757900000&lat=48.7769&lon=9.1844&mode=0
vs:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo%2CWe%2CTh%2008%3A00-12%3A00%20open%2C%20Mo%2CWe%2CTh%2013%3A30-15%3A00%20open%20%22Diabetologie%22%2C%20Mo%2CWe%2CTh%2016%3A00-18%3A00%20open%20%22Allgemeinmedizin%22%3B%20Tu%2008%3A00-12%3A00%20open%20%22Allgemeinmedizin%22%2C%20Tu%2013%3A00-16%3A00%20open%20%22Diabetologie%22%2C%20Tu%2016%3A00-18%3A00%20open%3B%20Fr%2008%3A00-12%3A00%3B%20PH%20off&lat=48.7769&lon=9.1844&mode=0

PS: offtopic: Beispiel aus diesem Thread: http://forum.openstreetmap.org/viewtopic.php?pid=586649#p586649 vielleicht magste ja ma rüber schauen, scheint mir dezent komisch, aber hab mir dazu schon reichlich den Kopf zerbrochen

**Comment by dex2000** [comment]
Arr, i mean the evaluation-tool.

**Comment by ypid** [comment]
Sounds good. I would just go with variant 4 which I proposed in PR #216 and which can be discussed and which I would merge the next days.

1. About checking if the date is very close to the current date when creating the permalink and dropping the timestamp in that case. This does not sound like a good default to me. After all, this is supposed to be a permalink. I usually use the permalink option when I want to refer to one specific thing which usually occurs at a specific time.

5. Not sure if such a distinction is necessary. Also not sure if a warning is needed. The tool has a very basic/clean design and shows the date and time it uses.

2. Two separate permalinks. I will keep this in mind when I come to the UI redesign.
