### ISSUE TITLE
Stable week cannot be iterated

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#158]
I have  (I know it could be written as `24/7`, but it comes from a 3rd party system)

`Mo 00:00-24:00; Tu: 00:00-24:00; We 00:00-24:00; Th 00:00-24:00; Fr 00:00-24:00; Sa 00:00-24:00; Su 00:00-24:00`

I want to display the current weeks opening table in `react` so I do:

```jsx
const stable = openingHours.isWeekStable()
  let today = new Date()
  today.setHours(0,0,0,0)
  let start, end
  if (onlyToday) {
    start = moment(today).startOf("day").toDate()
    end = moment(today).endOf("day").toDate()
  } else {
    start = new Date(today)
    start.setDate(start.getDate() - start.getDay() + 1) // Beginning of week
    end = moment(start).add(7, "days").toDate()
  }

  const rows = openingHours.getOpenIntervals(start, end).map(([from, to, unknown, comment], index) => (
    <tr key={index} style={from.getDay() == today.getDay() ? {...STYLES.today, ...todayStyle} : {}}>
      <td>{moment.weekdays(from.getDay())}</td>
      <td>{moment(from).format("LT")}</td>
      <td>-</td>
      <td>{moment(to).format("LT")}</td>
    </tr>
  ))
```

However this only outputs one row with `Monday 00:00 - 00:00`
Is that the correct behaviour?
However when Sunday is closed, its not included in the opening_hours string and the timetable is missing the Sunday row.

**Comment by ypid** [comment]
> Is that the correct behavior?

Yes. The library works as I would expect it. It correctly interprets `Mo 00:00-24:00; Tu: 00:00-24:00; We 00:00-24:00; Th 00:00-24:00; Fr 00:00-24:00; Sa 00:00-24:00; Su 00:00-24:00` as being equivalent to `24/7` end only returns you one interval. The code in this repo used to display the time table of the evaluation tool might help you out.

> However when Sunday is closed, its not included in the opening_hours string and the timetable is missing the Sunday row.

What do you mean by that? When I tested this, it worked perfectly find and the Sunday was reported as being open as well.

**Comment by ypid** [comment]
Closing. Feel free to reopen/comment.
