### ISSUE TITLE
isEqualTo returns array and not object as stated in docs

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#161]
given that `other` is "24/7" too, the `result` of the function call below yields: 

```
Array[1]
  0: true
```

```
const _247 = new opening_hours("24/7")

export const is24_7 = (other) => {
  const result = to_opening_hours(other).isEqualTo(_247)
  return result
}
```

What's going on? The docs specify that an object with the differences ought to be returned or `true`

**Comment by pke** [comment]
ok, nevermind. I misread the docs. Maybe clarify that the function always returns an `Array` with one (or more?) members. If the two OH are equal in meaning, then the only item in the returned `Array` contains `true`. Otherwise the returned `Array` contains one (or more?) objects describing the differences between the two OHs.

I wonder why the function not simply returns `true` or a list of differences, thats how I read the docs (not very careful).

**Comment by ypid** [comment]
> I wonder why the function not simply returns true or a list of differences, thats how I read the docs

I wanted to keep it flexible. For me as the one who wrote the docs, it is clear. Please go ahead and improve the docs from the perspective of a user of the lib. I might be blind to certain things. Sorry for that.
