### ISSUE TITLE
Relax optional dependency to moment.js

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#164]
I recently wondered why 2 version of `momentjs` where bundled in my app.
Then I checked this `package.json` here and saw:

```
optionalDependencies: {
  "moment": "2.10.6",
}
```

Could you please change that to a proper `semver` like `^2.10.6` or is there any reason why you fixed it at that version?
Current version is `2.13.0` and we would not end up with 2 versions included in bundles.

**Comment by ypid** [comment]
I intended update dependence version as they have been tested. But you are right. Using [semver](http://semver.org/) is a good idea. Want to make a PR?

**Comment by pke** [comment]
Sure, #165

**Comment by ypid** [comment]
Closed by #165.

**Comment by ypid** [comment]
Thanks for bringing that issue to my attention. I now use caret ranges for all dependencies which seems like a good idea. @pke What do you think?

**Comment by pke** [comment]
Generally yes. If breaking changes are only coming with major version increases then everybody sounds be safe. Carret does not update to major versions.
