### ISSUE TITLE
Added Nominatim URL to holiday_definitions.

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#167]
- [x] Update [docs](https://github.com/opening-hours/opening_hours.js/blob/master/docs/holidays.md#deciding-which-holidays-do-apply).
- [x] Add Nominatim URL to `holiday_definitions`.
- [x] Drop definitions in [js/nominatim_definitions.js](https://github.com/opening-hours/opening_hours.js/blob/master/js/nominatim_definitions.js) and [test.js](https://github.com/opening-hours/opening_hours.js/blob/master/test.js)
- [x] Write script/Makefile to build/get current data from Nominatim

Data format proposal (example):

```
'Mato Grosso': { /* {{{ */
    '_nominatim_url': 'https://nominatim.openstreetmap.org/reverse?format=json&lat=-10.4276788&lon=-52.0892082&zoom=18&addressdetails=1&accept-language=pt,en',
    'PH': { // https://pt.wikipedia.org/wiki/Feriados_no_Brasil#Feriados_estaduais
```

**Comment by adrianojbr** [comment]
i didn't understand how to find the nominatim url. can you explain?

**Comment by ypid** [comment]
Sure. Thanks for asking. Hope this helps: https://github.com/opening-hours/opening_hours.js/blob/master/docs/holidays.md#deciding-which-holidays-do-apply
