### ISSUE TITLE
Q - Get opening hour rules for week

### ISSUE THREAD

**Issue by LinkOut** [opening-hours/opening_hours.js#168]
Hi, i ve read the docs, but its pretty complicated, how i can get the opening hours rules per week, to i know day by day close and open time?

Thanks.

I wanna somethin like < day,open,close > x7

**Comment by dex2000** [comment]
dont understand the problem, can you give an example?

**Comment by ypid** [comment]
I am not quite following either so I try to address both possibilities:

* Get evaluated opening_hours for a time range of one week. Check https://github.com/opening-hours/opening_hours.js#synopsis and https://github.com/opening-hours/opening_hours.js/blob/master/js/opening_hours_table.js to get started.
* Get the rules which apply for the given days of a one week range. Check `oh.getMatchingRule`.

**Comment by LinkOut** [comment]
Sorry, my english is not so good. 

By giving a osm string to a function, i wanted that function to return me an array of days, with matching opening hours for that day. By testing i found **getOpenIntervals**. 

 var intervals = oh.getOpenIntervals(from, to);

What i'm doing then is loop through the intervals, and for each interval getting the current day open and close time (That's what i am looking for). 

Is this a correct approach?

Actually what i was looking for is something like this: 

[
{
"day":"dayName",
"morning":{
"open":"hh:mm",
"close":"hh:mm"
},
"afternooon":{
"open":"hh:mm",
"close":"hh:mm"
}
}
]

**Comment by ypid** [comment]
> Is this a correct approach?

Sure, you can do that. `oh.getOpenIntervals` should be the easiest way to get started. There is also the [Iterator API](https://github.com/opening-hours/opening_hours.js#iterator-api) which should be proffered if you want to get more advanced.

**Comment by ypid** [comment]
@LinkOut Do you have further questions? If not can you close this issue for now?

**Comment by LinkOut** [comment]
I've made a simply parser that do does this job atm is not the last version : https://github.com/digitalxmobile-dev/osmopeninghours 

Thanks for the support i really appreciate it.

**Comment by ypid** [comment]
Interesting, thanks. I added it to the [Used by other projects](https://github.com/opening-hours/opening_hours.js#used-by-other-projects) section.
