### ISSUE TITLE
English error messages for all errors

### ISSUE THREAD

**Issue by don-vip** [opening-hours/opening_hours.js#170]
When validating `opening_hours=5hs à 24hs` all users face error message "S'il vous plaît utiliser "-" pour "à" but only French users understand it.

Can you please provide an English error message even for language-specific errors?

From https://josm.openstreetmap.de/ticket/13145

**Comment by ypid** [comment]
Hey @don-vip 

Thanks for reporting. I had this somewhere on my todo but can’t find it right now in the issues. The input tolerance was done before translation to the lib was added. To solve this, the input tolerance would need to be refactored.

**Comment by don-vip** [comment]
#107 and #122 maybe?

**Comment by ypid** [comment]
Those must be it. Thanks for referencing them.

I can currently not say when I will get the chance to solve this. Maybe I can get into [v3.5.0](https://github.com/opening-hours/opening_hours.js/milestone/10) but I am not to sure yet.

**Comment by ypid** [comment]
Fixed by commit https://github.com/opening-hours/opening_hours.js/commit/0beaf07d9acec884f61a2c47684c5e67bd5d84e7
