### ISSUE TITLE
add compare-input to permalink (evaluation-tool)

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours.js#173]
would be nice, if the compare-data on input-field added to existing or new permalink

**Comment by ypid** [comment]
Sounds good. Should be fairly easy to do. Want to give it a try?

Hört sich gut an. Sollte sich einfach umsetzen lassen. Willst du es versuchen?

**Comment by dex2000** [comment]
Uhm, no.
sorry, da fehlt mir der Überblick und JS is auch nich so meins :(

**Comment by ypid** [comment]
ok, no problem
