### ISSUE TITLE
12 hour AM/PM time format parsed wrong

### ISSUE THREAD

**Issue by samdark** [opening-hours/opening_hours.js#183]
Time at 12 hour AM/PM is parsed wrong.

- 12:xxAM is converted to 12:xx while it should be 00:xx in 24 hour format. 
- 12:xxPM is converted to 00:xx while it should be 12:xx in 24 hour format.

The usual AM/PM timeline looks like the following:

```
12AM   12:01AM
0AM     0:01AM      1AM     12PM   12:01PM       11:59PM
 |        |          |       |        |            |
--------------------------------------------------------
            AM               |                 PM
```

**Comment by ypid** [comment]
Thanks for reporting! [Wikipedia](https://en.wikipedia.org/wiki/12-hour_clock) has a nice comparison of the 24-hour format and the am/pm system (what I consider a deprecated time format :wink:).

**Comment by samdark** [comment]
Thanks for the quick fix! Will test it Monday.

**Comment by ypid** [comment]
You are welcome. This was a bug which possibly lead to wrong data in OSM and thus had priority :wink:

**Comment by samdark** [comment]
Verified that it works fine. Thanks!
