### ISSUE TITLE
Update deprecated i18next-client to 2.0.0

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#187]
```
npm i opening_hours
WARN deprecated i18next-client@1.11.1: you can use npm install i18next from version 2.0.0
```

Not sure if it breaks something though.

**Comment by ypid** [comment]
I am not really in an urge to update but I guess when you use this lib together with other dependencies and so on you would like to use unified versions. Want to give it a try?

**Comment by ypid** [comment]
Superseded by: #232
