### ISSUE TITLE
clean up npm package

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#188]
Currently there are a bunch of test files in the published package.
I guess they should not be published, and go to .npmignore 

![image](https://cloud.githubusercontent.com/assets/164625/19158337/9e624c24-8be8-11e6-8d80-1ac870807a55.png)

**Comment by ypid** [comment]
Good point. The repo has become really messy. Should be split into lib core, osm testing tools and evaluation tool repos.

**Comment by ypid** [comment]
Fixed in https://github.com/opening-hours/opening_hours.js/commit/3faa31062b3b263ce71288604b11f1143dbf1d18, I tried searching the issues for `test.en.log` because I knew you had opened an issue for it but could not find the issue. Anyway, thanks!
