### ISSUE TITLE
Update German SH

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#192]

**Comment by ypid** [comment]
I looked into it. The data source http://www.schulferien.org I used October 2013 to do the initial and last SH import for Germany does not provide SH calender files that far into the future anymore as it did back in 2013. Officially, it does only provide files for the current year and the last year (kidding me?). Unofficially, the files for 2017 can already be downloaded and seem to be valid. This is not very satisfying. In 2013 I imported once and was done for 4 years.
Is there any better Open Data we can use?

**Comment by ypid** [comment]
I looked deeper into this, unfortunately, Germany or the Kultusministerkonferenz does not seem to provide school holidays as Open Data.

School holidays for all German Bundeslands until 2024 are defined (ref: http://www.spiegel.de/lebenundlernen/schule/sommerferien-kultusminister-legen-ferien-ab-2018-fest-a-974817.html)

Official data source: https://www.kmk.org/service/ferien.html (only published as PDF)
kmk.org links to the websites of the individual Bundeslands. "individual" is the key point here because each one has there own style of publishing them (either HTML or PDF).

Secondary data sources:

* http://www.schulferien.org/deutschland/ical/ (see my initial post, icals are only available up to 2017, I will contact the admins of the site as this would be the preferred source)
* https://de.wikivoyage.org/wiki/Schulferien_in_Deutschland (Page which includes MediaWiki tables of school holidays, could be parsed with some effort)
* http://www.kalenderpedia.de/ferien/ferien-2018.html (HTML table, other than that the format might change, only provides MS and PDF exports so nothing rational)
* http://www.schulferien.eu/downloads/ferien-im-ical-format/ (Similar to www.schulferien.org but not yet up-to-date with the SH defs 2018-2024)

**Comment by ypid** [comment]
The people behind http://www.schulferien.org answered. That upcoming iCal are not for download yet is on purpose. As they described, the website is financed with ads and the people downloading the iCal usually don’t contribute much in this regard. They also noted that an option might be added after paying something. I explained my use case and even wrote a price I might pay (23 €), no response yet.

Here is my initial message for transparency reasons:

> Schulferien als iCal bis 2024
>
> Sehr geehrte Damen und Herren,
>
> ich wollte Fragen, ob es eventuell möglich ist, die iCal Dateien für die deutschen Schulferien bereits im Vorfeld zu erzeugen und auf http://www.schulferien.org/deutschland/ical/ anzubieten? Die Dateien müssten nicht zwingen verlinkt sein, um den normalen Benutzer nicht zu verwirren. Wie ich der Tabelle "Aktuelle Ferien und Feiertage" auf http://www.schulferien.org/ entnehmen kann, haben Sie die Schulferien bereits im System.
> Hintergrund der Frage ist, dass ich die Schulferien gerne aus einem Programm, welches Öffnungszeiten [1] für OpenStreetMap auswertet benutzen würde [2] [3] [4].
> Mittels dieses Programms werden auch listen generiert, die dann wiederum von Schulen für die Automatisierung der IT und Computer benutzt werden [5].
>
> PS: Vielen Dank für schulferien.org. Die Seite hat mir sowohl als Schüler bis 2012 als auch danach für die Öffnungszeiten in OpenStreetMap (ein Hobby von mir) sehr geholfen!

[1]: https://wiki.openstreetmap.org/wiki/DE:Key:opening_hours
[2]: https://openingh.ypid.de/evaluation_tool/?EXP=SH%3B%20PH%20off&DATE=1471961280000&lat=48.7769&lon=9.1844&mode=0
[3]: https://openingh.ypid.de/
[4]: https://github.com/opening-hours/opening_hours.js
[5]: https://github.com/anschuetz/linuxmuster/tree/master/schultag

I was just going to start writing a Python package/CLI script which could parse the HTML table on http://www.schulferien.org/ when I discovered the fine https://github.com/wintermeyer/www.mehr-schulferien.de project. I will check that out and hopefully have something for long-term.

**Comment by ypid** [comment]
Postponing the issue a bit. I will do this in 2017-01.

**Comment by pke** [comment]
Pitty the German e-gov ambitions are sooo low. Did you try to reach the KMK directly and ask for OpenData sources?

**Comment by ypid** [comment]
I did not. Can you try it?

**Comment by pke** [comment]
Done.

**Comment by ypid** [comment]
Thanks! Btw. the guys from http://www.schulferien.org answered and said that they also don’t have machine readable data sources, but they have contacts to the different "Ministerien" or they do it manually. Lets see what the KMK says :wink: Would be nice to work out a actual solution.

**Comment by pke** [comment]
Answer from KMK in German

>vielen Dank für Ihre Anfrage vom 13.02.2017.
Es tut mir leid, Ihnen mitteilen zu müssen, dass die Kultusministerkonferenz die Feriendaten aus
technischen Gründen lediglich als Übersicht im PDF-Format zur Verfügung stellt.

#neuland :(

**Comment by ypid** [comment]
Thanks for trying it anyway. Maybe the more people ask, the better. Not sure. Anyway. That problem has been solved with the "help" of www.schulferien.org already. Wanted to push the code today but well. Should be fixed in the next days.

**Comment by pke** [comment]
Ok. With the update the ph and sh are optional now? So that it further reduces the package size? I for one don't need no SH in my app and the data just sits there in the bundle wasting space and parsing time.

**Comment by ypid** [comment]
It is not. Check #143 if you want to help. But this should easy to do now with #198. If you want it, you could give it a try.
