### ISSUE TITLE
Don't use for...in at all for old browsers compatibility

### ISSUE THREAD

**Issue by shouze** [opening-hours/opening_hours.js#199]
Every use of `for...in` in this lib make it unusable with IE11:

![3a522928-ebda-11e6-8a9d-ef88d5c1339e](https://cloud.githubusercontent.com/assets/54712/22646343/2afa45f4-ec6c-11e6-9926-c322bad7cd27.png)

Should be fixed:
- [opening_hours.js#L4263](https://github.com/opening-hours/opening_hours.js/blob/01c3dd02927765d632fcc74375c83e7aa837faad/opening_hours.js#L4263)
- [opening_hours.js#L4315](https://github.com/opening-hours/opening_hours.js/blob/01c3dd02927765d632fcc74375c83e7aa837faad/opening_hours.js#L4315)

@ypid I can make a PR, what's your preference?

### 1. Classic for loop with idx increment
```js
for (var selector_ind=0; selector_ind<selector_elements.length; selector_ind++) {
   // ...
}
```

### 2. Object.hasOwnProperty assertion
```js
for (var selector_ind in selector_elements) {
    if (selector_elements.hasOwnProperty(selector_ind)) {
        // ...
    }
}
```

**Comment by ypid** [comment]
Thanks for reporting. As there is a pretty big PR queued (#198) I can fix this after #198 has been merged to avoid merge conflicts. "Object.hasOwnProperty assertion" looks good. I will go with this then.

**Comment by shouze** [comment]
@ypid ok thx, I would be pleased to help, #198 is pretty cool indeed to split & help maintaining this lib.

**Comment by shouze** [comment]
@ypid I've seen you've released 3.5.0 so does this mean it's a go for #198 merge and apply a fix for this issue? Tell me if you need some help.

**Comment by ypid** [comment]
Yes, that is the plan. I would like to block all other work until #198 has been merged to not complicate things. Thanks very much for your help. You are welcome to join the project and help out. Just have a look over the open issues or find something you want to work on. Thanks!

**Comment by shouze** [comment]
Ok you can assign me on this one I will send a PR immediately once #198 has been merged. Will try to help on [other issues](https://github.com/opening-hours/opening_hours.js/issues?q=is%3Aopen+is%3Aissue+milestone%3Av3.6.0) too.

**Comment by ypid** [comment]
Thanks very much and welcome! Can you talk abit about your use cases and in what you are particularly interested?

**Comment by shouze** [comment]
Thx!

Yes, about our use cases, we're using this lib:
1. server side: as a webservice in a very simple rest api to serialize/deserialize opening hours from/to string & structured data
2. client/browser side: to understand string expression (this is where I've noticed this bug in IE)... but I guess that on the mid/long term I guess that client side rendering will use the webservice (notably because it's a cost to download the lib on browserside vs webserive async call).

We're building a website builder product for hotel owners, which produces websites like this (demo) one:
http://rezzza.github.io/platform.karibbu/

**Comment by ypid** [comment]
Thanks for the insides, interesting. Are you parsing opening hours from OSM? In the demo you linked there was a google map :wink:

**Comment by shouze** [comment]
We don't parse from OSM ATM but - as we use the lib to capture their opening hours from our backend - I think we will be pleased to contribute adding/enriching OSM data layer with informations we collect from hotel owners that will use our service.

**Comment by ypid** [comment]
Any updates?
