### ISSUE TITLE
Create reactjs component

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#200]
Want to create a reactjs component for OSM opening-hours. It should be able to display the timetable of a week with all its exceptions.
Is the [opening_hours_table.js](https://github.com/opening-hours/opening_hours.js/blob/master/js/opening_hours_table.js) class in this repo a good starting point to model the component after?

Depends on: #206

**Comment by ypid** [comment]
Should be a starting point but it all looks a bit messy. There is no alternative to opening_hours_table.js currently so if you want to display timetables, then I guess it is the only starting point :wink: Feel free to put in your JS foo where the implementation is messy.

**Comment by ypid** [comment]
Seems ReactJS is worth supporting (again): https://github.com/facebook/react/commit/8c3cececb765a0a0ad8b0faca764ef30be494a74
Feel free to create a reactjs component.

**Comment by pke** [comment]
Yes the license change is a good change. However before implementing the table as a react component I'd like to be able to serialise opening_hourse data so it can be streamlined more efficient into such component and down the net.

**Comment by ypid** [comment]
Sounds good to me. I don’t need this so waiting for me is not helpful. Both issues are in milestone " world conquest". 😉

**Comment by robinmetral** [comment]
@pke Did you ever build this component?

**Comment by pke** [comment]
unfortunately not. Could not allocate any time to it and then ditched this lib for performance and size reasons.

**Comment by ypid** [comment]
@pke Would be interesting what you use now :wink: ?

**Comment by pke** [comment]
Just a very simple, self written parser that covers only a small syntax pattern of the spec.
