### ISSUE TITLE
Why is 24/7 generating a warning in complex format string?

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#204]
Using `Mo-Th 16:30-05:30, Fr 14:00+, Sa-Su 24/7` 
generates a warning that 24/7 is maybe not correctly interpreted.
The rule should be Mo-Th open from 16:30-05:30 except for Fridays where its open from 14:00 till end of day. And Sa-Su 24/7.
Whats the error in the format?

**Comment by ypid** [comment]
I think the [given warning](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Th%2016%3A30-05%3A30%2C%20Fr%2014%3A00%2B%2C%20Sa-Su%2024%2F7&DATE=1487716380000&lat=48.7769&lon=9.1844&mode=0) is already very clear:

> You used 24/7 in a way that is probably not interpreted as "24 hours 7 days a week". For correctness you might want to use "open" or "closed" for this rule and then write your exceptions which should achieve the same goal and is more clear e.g. "open; Mo 12:00-14:00 off"

`24/7` in my understanding does not allow exceptions. How can something be open 24/7 if it is closed for some time. Does not make sense, that is why the warning exists.

**Comment by HolgerJeromin** [comment]
We need 24/2 :-)

**Comment by pke** [comment]
@ypid haha you are right. It's too late. So the correct way would be to write "24h"?

**Comment by ypid** [comment]
I would go with [Mo-Th 16:30-05:30, Fr 14:00+, Sa-Su 00:00-24:00](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Th%2016%3A30-05%3A30%2C%20Fr%2014%3A00%2B%2C%20Sa-Su%2000%3A00-24%3A00&DATE=1487716380000&lat=48.7769&lon=9.1844&mode=0). Define a `PH` as well to make opening_hours.js fully happy :wink: (but note that the PH needs to be handled specially to also catch the times wrapping over midnight).

**Comment by pke** [comment]
Thanks. And if public holiday are not relevant?

**Comment by ypid** [comment]
Depends. I guess `PH off; Mo-Th 16:30-05:30, Fr 14:00+, Sa-Su 00:00-24:00` (no PH is applied) should be the variant you are looking for.

**Comment by pke** [comment]
Thanks!
