### ISSUE TITLE
possible to serialize opening hours object?

### ISSUE THREAD

**Issue by pke** [opening-hours/opening_hours.js#206]
So that it can be saved as JSON and sent over a network? This would allow to save expansive re-parsing. Does the lib support that?

**Comment by ypid** [comment]
It does not currently. This could be done by dumping the selector code (generated functions) somehow and read them back in in the constructor, but I guess more state is needed to be dumped like the token array.

**Comment by pke** [comment]
So the token array is not enough?

**Comment by ypid** [comment]
As mentioned: [No, it is not](https://github.com/opening-hours/opening_hours.js/blob/01dc38a237bbbecece1b6efdf7ee7567abecd5c5/index.js#L13-L389).

**Comment by pke** [comment]
No longer using opening_hours, cleaning up stale issues.

**Comment by ypid** [comment]
Leaving it closed as I am not interested in this feature. For reference, you probably switched to https://github.com/pke/simple-opening-hours. I guess such info is always interested for others reading this.
