### ISSUE TITLE
Supersede _nominatim_url?

### ISSUE THREAD

**Issue by simon04** [opening-hours/opening_hours.js#218]
I find the concept of `_nominatim_url` hard to grasp. As far as I understand it, the URL is used in order to
* extract lat/lng
* extract language for the query

We could define the following keys instead of `_nominatim_url`:
* `admin_center: [lat, lng]`
* `languages: ['en-GB', 'en']`

What do you think?

**Comment by ypid** [comment]
Could be but I don’t see a good reason to replace `_nominatim_url` by `admin_center` and `languages`. The advantage I see with `_nominatim_url` is that it is a URL that users can test directly whereas with your approach less advanced users (who don’t run the tools which would assemble `admin_center` and `languages` back to a URL) would have to do some copy pasting madness. Do you see advantage which would justify the change? One case I could think of would be if I wanted to use another Nominatim instance but for such a eventuality I could just do a search&replace. Note that this lib directly depends on this very Nominatim query/response.

**Comment by ypid** [comment]
Closing for now. I think `_nominatim_url` is ok for now but I see your point.
