### ISSUE TITLE
make "https" links active ("http"-links are working) on http://openingh.openstreetmap.de

### ISSUE THREAD

**Issue by my-na-me** [opening-hours/opening_hours.js#226]
Hi all,

I'm not sure if I'm right here about this matter. If not, please could you tell me other address to forward it.

I discovered any displayed links strings starting with "http" [2] for osm-tagging `website=*`and `contact:website=*` are working well, but it seems if the link string starts with "https" [1] it isn't working by using http://openingh.openstreetmap.de

Thank you & regards
MN

[1] https not working - means not clickable
![grafik](https://cloud.githubusercontent.com/assets/27923772/26065342/ddd80d36-3993-11e7-8ac3-92fe3bdada94.png)

[2] http working - means clickable
![grafik](https://cloud.githubusercontent.com/assets/27923772/26065227/89ee82fe-3993-11e7-9241-30caf3272269.png)

edit: insert code (`website=*`and `contact:website=*`)

**Comment by ypid** [comment]
That is embarrassing that the map did only handled legacy http links correctly. Fixed and deployed on both servers. https://github.com/opening-hours/opening_hours_map is the repo which tracks the map btw.

I had to use overpass-turbo to actually find a node which was tagged with opening_hours and a state of the art https website which is unfortunate. http://overpass-turbo.eu/s/p4L

**Comment by my-na-me** [comment]
Oh, so quick - thanks a lot!
