### ISSUE TITLE
Performance hints

### ISSUE THREAD

**Issue by mmd-osm** [opening-hours/opening_hours.js#237]
I noticed a few issues during performance testing, which I believe are related this this code: https://github.com/opening-hours/opening_hours.js/blob/master/Makefile#L338-L356

* You could reduce the download size by more than 50% adding something like `[fee!=no][fee!=yes][lit!=no][lit!=yes]`
* Some of your queries, especially DE-NW always fail, because they use too much memory (see https://github.com/drolbr/Overpass-API/issues/429). Suitable maxsize parameter setting needs to be added to your query. Code changes on Overpass side to reduce memory consumption will take much more time.
* If your job runs a few minutes after midnight and would be very close to the point in time you want to analyze, consider removing the  `[date:...]` setting altogether. This will significantly speed up the query, and the difference in object count is probably negligible. Also it will significantly reduce memory consumption on the server side.
* Activate regular expressions (OVERPASS_QUERY_USE_REGEX): this was at least 40% faster during my tests.

**Comment by ypid** [comment]
Thanks for the input! It will take me some time before I can look into this.
