### ISSUE TITLE
Wide interval with different years

### ISSUE THREAD

**Issue by Mziserman** [opening-hours/opening_hours.js#241]
Hello.

Currently you can't parse values like "2017 Jan-2018 Feb 10:00-11:00"
I am wondering if it's because the value is wrong or is it just not implemented ?

**Comment by ypid** [comment]
Hi

According to [specification v0.6.0 (see <date_from>)](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#date_from) value is wrong so I am not planing to implement it. Do you see a need for this? You can just express your value like this:

[`2017 Jan 01-2018 Feb 29 10:00-11:00`](https://openingh.ypid.de/evaluation_tool/?EXP=2017%20Jan%2001-2018%20Feb%2029%2010%3A00-11%3A00&lat=52.5221879&lon=13.4093313&mode=0)

**Comment by Mziserman** [comment]
Ok thanks, good to know that. I don't have a usecase but it just seemed logical to me since Jan-Feb is valid.

**Comment by ypid** [comment]
I guess you are right. It was specified like this when I got into opening_hours in OSM. Could be extended. You are free to get involved in the specification. There is definitely room for improvement.

Anyway. I am closing this issue for now.
