### ISSUE TITLE
Basic, extra open, extra closed openinghours.

### ISSUE THREAD

**Issue by AllroadsNL** [opening-hours/opening_hours.js#270]
Usually a company sets the opening hours for a year.
I appoint these as basic opening times.

Then he decides that he wants to be extra closed for a few days, you are going to use the term "year".
I appoint these as "extra_closed" opening times.

Or he decides to open an extra few days, you will use the term "year".
I appoint these as "extra_open" opening times.

The following hierarchy:
opening_hours = *
overrulled by
opening_hours: extra_closed
overrulled by
opening_hours: extra_open

extra_closed and extra_open could be checked if they overlap.

I think it will be better organized if you create categories,
that give a better insight into what they contain.
Fewer mistakes are made in the basic opening times setting.

I received an application to close some extra days and open some.
This did not fit within the characters, because of the use or "year". Problem!
I have the need to do it well, write down everything and keep it clear.
Example: If someone calls me, could you change a few dates, that should be easy without damaging the base tagging.
This will change from year to year. Then after a while you can remove from these two extra categories, the older dates, without tackling the base.

What do you think about that?

**Comment by ypid** [comment]
I don’t think I understand your use case. I would propose you ask this question either at the tagging mailing list or in the wiki talk page. This issue tracker is for issues or feature requests in the JavaScript library which parses/evaluates `opening_hours`. I try to follow the spec and what you describe is not specified as far as I know.

**Comment by matkoniecz** [comment]
I am not sure why you opened
https://github.com/opening-hours/opening_hours.js/issues/270
to discuss new tagging idea.

If you want to discuss new tagging ideas then post it on a tagging mailing list
or on OSM wiki discussion page.

**Comment by ypid** [comment]
@AllroadsNL Discussion about this topic is welcome. There is currently some discussion going on on the tagging mailing list about opening_hours again. Just make your proposal there.

After thinking about your input, I have something which might go into the direction of what you have in mind:

A shopping center/building with many small amenities in the building. The building might have opening hours by itself and the individual amenities as well. The building sets basic constraints and the amenities can only be open when the building is open. Shopping center is just one example, many other such cases come to mind.

If you are also interested in this, then I would encourage you to discuss this.

But as noted, this is not the right place and I am going to close this issue now.

**Comment by AllroadsNL** [comment]
Yes, the discussion about, in tagging list is okay.
A discussion in the field, shop, please change the opening hours, I am closed on that date.
A short easy to manage tag would be nice. That's, why my thoughts of splitting up.
Thinking about the .js, is there a possibility to do that, this was my intention to ask here.

@ypid
As you mentioned, a factory with more closing times. Delivery, office, etc.
