### ISSUE TITLE
HU translation

### ISSUE THREAD

**Issue by debyos** [opening-hours/opening_hours.js#275]
Dear All,

I have made some improvements in the [Hungarian translation](https://github.com/opening-hours/opening_hours.js/blob/a01d1678291f19034ef4f33d123b90f80bd31614/js/i18n-resources.js) of the opening hours map and evaluation tool. Since I can't edit the file I would like to ask you to upload it. [It's attached](https://github.com/opening-hours/opening_hours.js/files/2590793/i18n-resources.zip).
Thanks in advance

Gábor Babos

**Comment by ypid** [comment]
Thanks, deployed on http://openingh.openstreetmap.de :+1:

**Comment by debyos** [comment]
Dear All,
I have made some improvements in the [Hungarian translation file](https://github.com/opening-hours/opening_hours.js/blob/bcc86fac124179e825681baf5a3e0c7ed7caeddd/js/i18n-resources.js). You can 
[find it attached](https://github.com/opening-hours/opening_hours.js/files/3300808/i18n-resources.zip) Please, deploy it.
Thanks
Gábor

**Comment by ypid** [comment]
> Please, deploy it.

Hi

Thanks for the fix. Committed (in your name), pushed and deployed. Thanks.
