### ISSUE TITLE
"Not very explicit" warning with rule containing <rule modifier>

### ISSUE THREAD

**Issue by don-vip** [opening-hours/opening_hours.js#276]
Hello,
We [added](https://josm.openstreetmap.de/ticket/16525#comment:12) a new preset example in JOSM:
`Mar-Jun closed; Jul-Feb open`

We get the following warning:
`opening_hours - Mar-Jun closed; Jul-Feb open <--- (This rule is not very explicit because there is no time selector being used. Please add a time selector to this rule or use a comment to make it more explicit.) => Mar-Jun closed; Jul-Feb open`

From [this comment](https://github.com/opening-hours/opening_hours.js/issues/49#issuecomment-53915561) it looks like a false positive?

**Comment by ypid** [comment]
Sorry for the delay. I answered in the JSOM ticket directly. I am closing it here for now.
