### ISSUE TITLE
missing example for 2 opening periods within the same weekday 

### ISSUE THREAD

**Issue by my-na-me** [opening-hours/opening_hours.js#277]
Hallo Zusammen,

ich vermisse auf der Prüfseite:
http://openingh.openstreetmap.de/evaluation_tool/?setLng=de
im Kapitel für Beispiele, ein Beispiel welches die Syntax zeigt, wenn an ein und dem selben Tag zu zwei unterschiedlichen Zeiträumen geöffnet ist.

In der OSM-wiki von Key:opening_hours (https://wiki.openstreetmap.org/wiki/Key:opening_hours) habe ich einen Fall im 3. Beispiel gefunden:
https://wiki.openstreetmap.org/wiki/Key:opening_hours#Examples
kurz: "Mo 10:00-12:00,12:30-15:00"
lang: "Mo 10:00-12:00,12:30-15:00; Tu-Fr 08:00-12:00,12:30-15:00; Sa 08:00-12:00"

Es würde mich freuen, wenn dies jemand auf http://openingh.openstreetmap.de/evaluation_tool/?setLng=de nachtragen könnte.

Dankeschön!

**Comment by ypid** [comment]
Danke dir für den Hinweis :+1: Eventuell sollte ich einen Automatismus bauen, um gute Bespiele aus anderen Quellen zu integrieren. Eventuell aus dem Testframework. Bis dahin habe ich die zwei Beispiele von dir manuell aufgenommen.

**Comment by my-na-me** [comment]
Dankeschön :-)
