### ISSUE TITLE
Japanese Holidays

### ISSUE THREAD

**Issue by surgicalmaskman** [opening-hours/opening_hours.js#278]
In Japan, 16 public holidays (and more). those holidays applicable all areas.
see https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html (japanese lang.) https://eco.mtk.nao.ac.jp/koyomi/faq/holiday.html.en (english).

`
'jp': {
  'PH': {
    "元日":  [1, 1]
    "成人の日": [firstJanuaryMonday, +7]
    "建国記念の日": [2, 11]
    "春分の日": []
    "昭和の日": [4, 29]
    "憲法記念日": [5, 3]
    "みどりの日": [5, 4]
    "こどもの日": [5, 5]
    "海の日": [firstJulyMonday,  +14]
    "山の日": [8, 11]
    "敬老の日": [firstoctOberMonday, +14]
    "秋分の日": []
    "体育の日": [firstDecemberMonday, +7]
    "文化の日": [11, 3]
    "勤労感謝の日": [11, 23]
    "天皇誕生日": [12, 23]
  }
}
`

春分の日 and 秋分の日 is determined astronomically observation. I didn't write, becouase I don't know  notation. thanks.

**Comment by ypid** [comment]
Hi @surgicalmaskman 

Thanks very much. Please have a look at the current documentation https://github.com/opening-hours/opening_hours.js/tree/master/holidays. The holiday definition format has been changed to YAML. Also a few other fields are required.

Feel free to post the full holiday definition in this issue and I will integrate it into the library. Thanks!

**Comment by ypid** [comment]
> two days is not calculable.

Hm. As you posted the file, it is not valid YAML so I can not simply use it. We need to agree on something and I would suggest to just define both dates:

```YAML
 - {'name': '1. 春分の日', 'variable_date': [3, 20]}
 - {'name': '2. 春分の日', 'variable_date': [3, 21]}
```

Does that work for you? I am probably a bed person to decide this as I have limited local knowledge. Same would go for the other case.

**Comment by miurahr** [comment]
These holidays are known as related to solar term
https://en.wikipedia.org/wiki/Solar_term

春分の日 (ja-Latn: Shunbun-no-Hi) is a spring equinox, and defined by government in each year.
https://en.wikipedia.org/wiki/March_equinox

秋分の日 (ja-Latn: Shûbun-no-Hi) is an automn equinox.

These are able to calculate using `astoronomy` and you can see a result in GMT from 2001 to 2100 here.
http://www.astropixels.com/ephemeris/soleq2001.html

Japan government decide  holiday when a local time(JST) day has  each quinox exact time. 

I don't know how to define this in YAML, here is for your understandings.

**Comment by surgicalmaskman** [comment]
ah, I forget a link.
spring/fall equinox dates are unofficial provided [here](https://www.nao.ac.jp/faq/a0301.html) .
However, that is only a guide. official define by govnt gazette in the preceding year.

**Comment by shirayuki** [comment]
For Japanese holidays in 2019, see also:
https://en.wikipedia.org/wiki/Public_holidays_in_Japan

Additionally, holidays in 2020 are different than other years :(
Marine Day (海の日 Umi no Hi) - Jul 23, 2020
Sports Day (スポーツの日 Sports no Hi) - Jul 24, 2020
Mountain Day (山の日 Yama no Hi) - Aug 10, 2020

**Comment by tankaru** [comment]
As surgicalmaskman has shown, National Astronomical Observatory of Japan has calculated 春分の日(Vernal Equinox day) and 秋分の日(Autumnal Equinox day) until 2030 (https://www.nao.ac.jp/faq/a0301.html).
Those calculated days are not official ones, but I think those are reliable.

If PH accepts SH format, 春分の日 would be defined like this.

  - name: 春分の日
    '2018': [3, 21]
    '2019': [3, 21]
    '2020': [3, 20]
    '2021': [3, 20]
    '2022': [3, 21]

Is this acceptable?

**Comment by ypid** [comment]
Thanks guys for the clarification! I am not fully happy with the holiday definition format but at least starting with v3.0.0 it has been designed to be expendable. I would propose this PH format extension (`only_years`):

```YAML
- {'name': '春分の日', 'variable_date': [3, 20], 'only_years': [2018, 2019, 2022]}
- {'name': '春分の日', 'variable_date': [3, 21]}
```
Note this from the documentation:

> Order matters, "first come first serve"/"first rule wins" is used to determine the name of a holiday. Evaluation is done in sequence so if two PH definitions evaluate to the same date for a given year, then the first definition is used.

This also comes in handy here so we only have to list the years for [3,20].

Sounds good? If yes than I would go with that. Then please update the jp.yaml file and it can be included. If you someone wants to also implement and test the extension `only_years` you are welcome to give it a try otherwise I will do that when time permits.

**Comment by surgicalmaskman** [comment]
nice idea. I do update the files.

**Comment by surgicalmaskman** [comment]
resolved. #431
