### ISSUE TITLE
Use with Angular

### ISSUE THREAD

**Issue by andreadompe** [opening-hours/opening_hours.js#282]
Someones use it with angular?

**Comment by lamda** [comment]
I got it to working doing the following:
1. `npm install opening_hours`
2. `npm install moment i18next-client country-language`(optional, I guess)
2. add to angular.json:
`
            "scripts": [
              "node_modules/opening_hours/opening_hours.js"
            ]
`
3. import in component as `import * as opening_hours from 'opening_hours';`
4. use as described in the readme

**Comment by andreadompe** [comment]
Thanks @lamda

**Comment by ypid** [comment]
Seems to be solved.
