### ISSUE TITLE
Using opening_hours.js in node cli and esm

### ISSUE THREAD

**Issue by robinkeith** [opening-hours/opening_hours.js#295]
Can anybody advise how to use opening_hours.js from a node cli script please?

Currently I'm using opening_hours.js to prettify opening hours strings when adding an OSM extract to a Leaflet map.  

I want to speed things up by moving the prettify to an off-line pre-process of the OSM data, using node.  Node doesn't support the ES6 style modules include, other than an experimental mode that needs .js files renamed to .mjs. I found a utility called [ESM ](https://www.npmjs.com/package/esm)that gives a polyfill that seemed promising, but it spits in [holidays/index.js](https://github.com/opening-hours/opening_hours.js/blob/master/holidays/index.js) when it imports the yaml files as es6 modules.

Has anybody else got this working? Or any ideas to try? I tried doing a make on the project to get the final js but that didn't do anything.

Thanks in advance
Robin

**Comment by ypid** [comment]
Hi

Running this library from the Node CLI is something I do all the time for developing, testing and some cron jobs.

There are some scripts which you can call directly from the Node CLI like [interactive_testing.js](https://github.com/opening-hours/opening_hours.js/blob/master/interactive_testing.js). To me it sounds more like a Node setup issue. You can have a look at the Travis CI setup for a working example. What is your environment? GNU/Linux? Please provide more details ;-)

**Comment by robinkeith** [comment]
I got it working using opening_hours+deps.min.js  - the built, minified js includes the hours data. Just copied that file to my /src folder. Because the YAML is already included, it doesn't spit on including the yaml. So cheating!
Can I ask which locale you're using please? I'm on a Windows laptop.

**Comment by ypid** [comment]
Not sure what the effect the locale should have. I use and test mostly with en and de. Check out the working CI tests https://github.com/opening-hours/opening_hours.js/blob/master/.travis.yml

**Comment by ypid** [comment]
> I got it working using opening_hours+deps.min.js [...] So cheating!

Cheater :) But good for me because now I can close this issue as "Works for me/on my machine/on CI/everywhere else" :) Node.js supports Windows so it should work, but I don’t test on Windows.

> I'm on a Windows laptop.

You might still want to switch to a proper OS. https://getgnulinux.org/
