### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by thany** [opening-hours/opening_hours.js#297]
Would it be possible to get typescript definitions for, well, typescript? 😀
Otherwise every type coming out of opening_hours will be of type `any`, which is very undesirable in a typescript environment.

I've tried installing `@types/opening_hours`, but it doesn't exist.

**Comment by ypid** [comment]
> Would it be possible to get typescript definitions for, well, typescript?

To answer that question clearly, no, it is not possible to simply "get" typescript definitions (unless of course somebody does it). For me there are more urgent issues in this project and even they don’t get the time allocated from me that they deserve currently.

TL;DR: I am open for pull requests.

**Comment by MerlinPerrotLegler** [comment]
Hey @ypid,

I did the definition for typescript, but when I try to `yarn add https://github.com/MerlinPerrotLegler/opening_hours.js.git#feature/typescript-definition` (my repo)

I'm getting this error, so I'm not able to test :(

Any Idea ?

Regards

**Comment by ypid** [comment]
`yarn add` seems to be downloading your branch using a zip file or something. At least `husky` is missing the `.git` repo. I guess you can either try to `git clone` the repo and then use `yarn` or disable the `husky` in your branch. I am not an expert with neither of those tools.

**Comment by MerlinPerrotLegler** [comment]
Thanks, why didn't I think about this ^^'
PR is raised https://github.com/opening-hours/opening_hours.js/pull/399

**Comment by ypid** [comment]
Thanks @MerlinPerrotLegler! Merged.

> I've tried installing @types/opening_hours, but it doesn't exist.

Do I need to do something like publish that definition somewhere or can the issue be closed?

**Comment by MerlinPerrotLegler** [comment]
There is two ways to define types for a repository either directly in the repository (in the `package.json` as you now have) or through `@types` but norme are quite severe.
The first option is always the one to be preferred as user will only need one yarn/npm install.

**Comment by ypid** [comment]
Thanks for the clarification. I am closing this as solved then.

**Comment by MerlinPerrotLegler** [comment]
Hello @ypid,
I've tryed to change the dependency in some of my project from my fork to the original npm package but I dont see the result of the MR.
Could you make a new release or add a new version (I dont know how it's work).
While managing my private repo I'll use `yarn version --minor` in this case.
Regards

**Comment by ypid** [comment]
I guess I can do that, maybe tomorrow. I am not quite happy that only a few commits have happened https://github.com/opening-hours/opening_hours.js/commits/master and the changelog is also not really full https://github.com/opening-hours/opening_hours.js/blob/master/CHANGELOG.rst#master---unreleased, but why not.

**Comment by ypid** [comment]
Done that.
