### ISSUE TITLE
Create Web API for public/school holiday management

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#303]
In #300 it has been suggested to create a Open Data project that everybody (including opening_hours.js itself) could use to manage holiday definitions. Think of it like a central repository that definitions could be POSTed to and requested back. To be clear, I myself have no intention to implement that. Someone would need to step up and do it. I am more interested in merging with other existing data sources (ref: #300) or if that is not feasible, move our holiday definitions into a separate data project (without Web API) #71. But other members of the community are interested in this so I am open for discussion and support their work in this area.

API example:

```
POST /v0/de/bw/2019-12-23/2020-01-06?name=Weihnachstferien
```

For the initial discussion please refer to #300. The discussion about this API should be continued in this issue.

**Comment by pke** [comment]
I'll set a prototype up.

**Comment by ypid** [comment]
No interest from the community has emerged here. I close this.
