### ISSUE TITLE
How to translate evaluation_tool webpage ?

### ISSUE THREAD

**Issue by pyrog** [opening-hours/opening_hours.js#328]
How to translate https://openingh.openstreetmap.de/evaluation_tool ?
Especially the examples ?

**Comment by ypid** [comment]
This is answered by the README: https://github.com/opening-hours/opening_hours.js#translating-the-evaluation-tool-and-the-map

**Comment by pyrog** [comment]
@ypid I searched before writing this issue i.e. **"Beware of vampires!"** in [js/i18n-resources.js](https://github.com/opening-hours/opening_hours.js/blob/master/js/i18n-resources.js) without success 😉 

I discover this morning that `"comments"` in examples are not internationalised 😞 
Example : [index.html#L170](https://github.com/opening-hours/opening_hours.js/blob/master/index.html#L170)

**Comment by ypid** [comment]
Sorry that I misunderstood you.

> I discover this morning that "comments" in examples are not internationalised disappointed
Example : index.html#L170

You found one little spot that is not :) As comments are in local language, I am open to internationalize it as well.

**Comment by pyrog** [comment]
> little spot that is not

It is 😉 
Unfortunately a lot of french OSM contributors are not fluent in english.
And some exemples don't have any meaning in France.

So it will great if we could provide examples of the real life, in the natural language of users/contributors. 😃
