### ISSUE TITLE
HU translations

### ISSUE THREAD

**Issue by debyos** [opening-hours/opening_hours.js#332]
Dear All,

I have made some minor improvements on the [Hungarian translation](https://github.com/opening-hours/opening_hours.js/blob/449f11ba0ba84732266e0befacb2d9d25d08ff46/js/i18n-resources.js); you can find it [attached](https://github.com/opening-hours/opening_hours.js/files/4698080/i18n-resources.zip).
Please deploy it.
Thank you

_Debyos_

**Comment by ypid** [comment]
Deployed, thanks!
