### ISSUE TITLE
How to specify opening hours for i.e. summer and opening hours for rest of the year ?

### ISSUE THREAD

**Issue by pyrog** [opening-hours/opening_hours.js#338]
Sep-Jun

- Mo,We-Fr 10:00-12:00,14:00-18:00; Tu 14:00-18:00;

Jul-Aug

- Mo-Fr 10:00-12:00,14:00-18:30

`Sep-Jun: Mo,We-Fr 10:00-12:00,14:00-18:00; Tu 14:00-18:00; Jul-Aug: Mo-Fr 10:00-12:00,14:00-18:30` don't work : nly the first day described in a week work.

`Sep-Jun: (Mo,We-Fr 10:00-12:00,14:00-18:00; Tu 14:00-18:00); Jul-Aug: (Mo-Fr 10:00-12:00,14:00-18:30)` don't work at all.

**Comment by dex2000** [comment]
You have to repeat the month-range; https://openingh.ypid.de/evaluation_tool/?EXP=Sep-Jun%3A%20Mo%2CWe-Fr%2010%3A00-12%3A00%2C14%3A00-18%3A00%3B%20Sep-Jun%3A%20Tu%2014%3A00-18%3A00%3B%20Jul-Aug%3A%20Mo-Fr%2010%3A00-12%3A00%2C14%3A00-18%3A30&lat=48.7769&lon=9.1844&mode=0&DATE=1598882880000

**Comment by pyrog** [comment]
Sorry, I tested this week but tomorrow is september ! 😆 
<img width="940" alt="Screen capture" src="https://user-images.githubusercontent.com/2158081/91734102-c3ca3c80-ebaa-11ea-9ec1-fab8bc411f1a.png">
