### ISSUE TITLE
Cannot check date on school holidays in Poland, województwo podlaskie.

### ISSUE THREAD

**Issue by dbadura** [opening-hours/opening_hours.js#344]
When I tried to parse time in such format:
`SH on Tu-Su 09:00-17:00,13:00-13:30; SH off Tu-Su 08:00-16:00,13:00-13:30`, I got following error:
```
An error occurred during evaluation of the value "SH on Tu-Su 09:00-17:00,13:00-13:30; SH off Tu-Su 08:00-16:00,13:00-13:30". Please submit a pull request: https://github.com/opening-hours/opening_hours.js. There are no holidays (SH) defined for country pl and state województwo podlaskie.
```
I used:
https://openingh.openstreetmap.de/evaluation_tool/?&lat=52.7769&lon=19.1844&setLng=pl#check

How this problem can be fixed?

**Comment by ypid** [comment]
Hi there. Have you read the README https://github.com/opening-hours/opening_hours.js#holidays-1 ? :wink:, it says that no issue does need to stay open for each of the hundred missing holiday definitions (for the different countries). I am closing this issue therefore. Feel free to add the missing SH definition. Ref: https://github.com/opening-hours/opening_hours.js/blob/master/holidays/pl.yaml
