### ISSUE TITLE
How to initialize 'opening_hours' if country and location are known?

### ISSUE THREAD

**Issue by pietervdvn** [opening-hours/opening_hours.js#345]
Hey,

I want to add opening-hours support to MapComplete, and this project is perfect for that!

I already have the coordinate of the points and the country. How do I initialize opening_hours? Should I rebuild a 'nominatim-object'?

TBH: I didn't search very good in the documentation...

Thanks in advance!

**Comment by pietervdvn** [comment]
Turns out that `{lat: <some number>,lon: <some number>,address: {                country_code: <some country code>            }        }` is enough

**Comment by ypid** [comment]
Hi, sorry for the late reply. Do the docs need to be improved? Ref: https://github.com/opening-hours/opening_hours.js#library-api

**Comment by pietervdvn** [comment]
No problem.
I just sent out a PR with IMHO the needed improvements (#346).
