### ISSUE TITLE
Italian day name not recognised

### ISSUE THREAD

**Issue by Mannivu** [opening-hours/opening_hours.js#375]
The tool seems to not recognise the Italian day name "Domenica" (en: Sunday), but when I use "Do" it gets converted to "Th" (probably, the systems reads it as "Donnerstag" which is German for "Thursday").
![image](https://user-images.githubusercontent.com/42747216/106785317-9009ac00-664d-11eb-8979-4323b7c3e5f8.png)
Moreover, the system understands correctly "Lun" (probably from Spanish "Lunes") "Mer" and "Ven" (probably from French "Mercredi" and "Vendredi"), but doesn't work with "Mar", "Gio", "Sab" and "Dom"

**Comment by ypid** [comment]
The rules are in this file https://github.com/opening-hours/opening_hours.js/blob/master/locales/word_error_correction.yaml. Can you update it? Note that some translations are not possible because they conflict between different languages (Do from your example).

**Comment by Mannivu** [comment]
Yes, no problem. I'll update that file. Thanks!

**Comment by ypid** [comment]
Thanks.

Closed by: #376
