### ISSUE TITLE
Additional rule of a new normal rule should override a previous normal rule

### ISSUE THREAD

**Issue by goodudetheboy** [opening-hours/opening_hours.js#401]
This is the result from parsing `Tue,Thu 07:00-14:00; Mo,We,Fr 09:00-13:00, Tue,Thu 12:00-13:00`

![image](https://user-images.githubusercontent.com/8723281/122588109-e28db700-d088-11eb-8f7f-4c1839aaca53.png)

Shouldn't it make more sense if `Tue,Thu 12:00-13:00` override `Tue,Thu 07:00-14:00` (so Tue and Thu's opening time would be from 12:00-13:00 instead of 07:00-14:00), since it's a part of a new normal rule?

**Comment by dex2000** [comment]
If you want to override something, you have to use the semicolon: ; instead of comma

**Comment by goodudetheboy** [comment]
Oh okay, I thought the comma was to add an extension to a normal rule, but after reading the specs again it was a rule separator.
