### ISSUE TITLE
Typescript issue with optional_conf mandatory mode property

### ISSUE THREAD

**Issue by frodrigo** [opening-hours/opening_hours.js#428]
The interface `optional_conf` require the `mode` property.

But from the doc, the `mode` is not mandatory and could be deduced from `tag_key`.

I suggest to make it optional.

**Comment by ypid** [comment]
Closed by #429
@frodrigo Hint: If you include a note in your commit message like `closes #428`, GitHub would have auto closed this issue on merge.
