### ISSUE TITLE
Bulgarian public holidays

### ISSUE THREAD

**Issue by Dimitar5555** [opening-hours/opening_hours.js#437]
Non-working days:
1 January - New Year
3 March - Liberation day
Orthodox Easter (in most cases one week after the Catholic Easter, but there were cases where they were on the same dates, as well as cases of them being a month apart)
1 May - Labour Day 
6 May - St. George's Day, Day of Bravery and the Bulgarian Army
24 May - Day of Bulgarian Enlightenment, Culture and the Slavonic Script
6 September - Unification of Bulgaria
22 September - Independence Day of Bulgaria
24, 25 and 26 December - Christmas. If 24 is Saturday, 27 and 28 are also non-working days, if 24 is Sunday 27 is non-working day

For all 1-day holidays, if it happens that this day is a Saturday or Sunday, the next Monday is non-working day.

**Comment by ypid** [comment]
Sorry, I have to close this because I am only one maintainer in my spare time. See: https://github.com/opening-hours/opening_hours.js#holiday-data

See also: #300
