### ISSUE TITLE
Allow prettify to output 12 hour (AM/PM) time

### ISSUE THREAD

**Issue by michaelkirk** [opening-hours/opening_hours.js#439]
I'd like to be able to localize opening hours to whatever conventions the user has.

Unless I've missed it, it's not possible to format times in the 12 hour format.

**Comment by ypid** [comment]
I would rather say that the way you input AM/PM times are not supported. [Mo-Fr 10am-8pm](https://openingh.ypid.de/evaluation_tool/?EXP=Mo-Fr%2010am-8pm) is supported and will get prettified correctly. You should have written a better issue text and included examples to avoid me having to guess.

Side note: I currently don‘t dedicate time to develop new features like this on. You would have to contribute it if you want to see it happening :)
