### ISSUE TITLE
People may not expect, that public holiday overwriting rule, overwrites times from the day before going into the PH

### ISSUE THREAD

**Issue by fabi003** [opening-hours/opening_hours.js#441]
This is not a bug, but maybe a usability problem when writing opening_hours rules and the time from the day before the public holiday goes over midnight and into the public holiday.

To illustrate the issue, look at the linked rule for Germany, where this year the 1st May, which is a public holiday, was a Monday.

https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2018%3A00-03%3A00%2C%20Sa%2CSu%2019%3A00-02%3A00%3B%20PH%20off&lat=54.2&lon=13.4&mode=0&DATE=1682885880000#

As the facility is open on Su from 19:00-02:00, the ";PH off" rule overwrites the time from the day before, so it is not open from 00:00-02:00 on the PH.

If you leave out a rule for PH the evaluation website gives this advice:

"Mo-Fr 18:00-03:00, Sa,Su 19:00-02:00 <--- (There was no PH (public holiday) specified. This is not very explicit. Unfortunately the tag key (e.g. "opening_hours", or "lit") is unknown to opening_hours.js. This warning only applies to the key opening_hours. If your value is for that key than read on. If not you can ignore the following. Please either append a "PH off" rule if the amenity is closed on all public holidays or use something like "Sa,Su,PH 12:00-16:00" to say that on Saturdays, Sundays and on public holidays the amenity is open 12:00-16:00. If the amenity is open everyday including public holidays then you can make this explicit by writing "Mo-Su,PH". If you are not certain try to find it out. If you can’t then do not add PH to the value and ignore this warning.)"

So it is no good idea to generally recommend writing something like "; PH off" if some of the times goes over midnight. The same issue affects "Sa,Su,PH 12:00-16:00", as the additional PH rule is a problem, when e.g. the remaining rule is e.g. "Mo-Fr 11:00-16:00", so with "Mo-Fr 11:00-16:00, Sa,Su,PH 12:00-16:00" the facility is open from 11:00-16:00 if the PH is between Mo and Fr.

For may above example to be correct, it must be written:
"Mo-Fr 18:00-03:00, Sa,Su 19:00-02:00; PH Mo-Fr 00:00-03:00, PH Sa,Su 00:00-03:00"
https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2018%3A00-03%3A00%2C%20Sa%2CSu%2019%3A00-02%3A00%3B%20PH%20Mo-Fr%2000%3A00-03%3A00%2C%20PH%20Sa%2CSu%2000%3A00-03%3A00&lat=54.2&lon=13.4&mode=0&DATE=1682885880000#

Yes, you have to write an extra rule for every time range, which may end at the public holiday! This can be a problem with the 255 char limit of OSM, when you also have to write comments.

As also example 4 on the evaluation page shows, many people (me first included) are not aware, that the code works correct in this kind.

Later addition/edit:
According to the spec (https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#Explanations) when the holiday rule is additional with ", PH off", the times from rules before should not be overwritten, but with 
https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2018%3A00-03%3A00%2C%20Sa%2CSu%2019%3A00-02%3A00%2C%20PH%20off&lat=54.2&lon=13.4&mode=0&DATE=1682885880000#
the facility is also closed all PH long, so this seems to be a bug.

**Comment by ypid** [comment]
> For may above example to be correct, it must be written:

I would write it as:

> Mo-Fr 18:00-03:00, Sa,Su 19:00-02:00; PH 18:00-03:00 off

<hr>

>  when the holiday rule is additional with ", PH off", the times from rules before should not be overwritten

I don’t see a bug. Additional rules only work for status open. For closed, they are the same as `<normal_rule_separator> `.

**Comment by ypid** [comment]
If you want to, you can improve the warning message.

**Comment by fabi003** [comment]
This is more a usability issue, as I have written above, all rules which goes over midnight, can potentially overwritten by a “, PH off” or “; PH off” which is maybe a common mistake, and a case for an overwriting warning.

The wrong example 4 on the evaluation website (“Fr-Sa 18:00-06:00; PH off”), which must be “Fr-Sa 18:00-06:00; PH Fr-Sa 00:00-06:00” as the facility is closed after midnight, if the PH is on Sa or Su, just illustrates, that this overwriting is hard to spot.

So if there is a fixed date (possible hard to spot normal overwriting) or variable weekday closing rule (PH, SH, easter), then you have to repeat all weekday rules, with times over midnight, with an extra rule for this closing day from midnight to the end time on the closing day. Because of this variability, I have no idea for a static explanation text.

At least should be warned about it, as writing “; PH off” is OK and very common (at least in Europe), when the time doesn't go over midnight, so people as me first, don't think that this is an issue.

**Comment by ypid** [comment]
Good catch. We cannot leave wrong examples like that on the page. Also, I made an attempt at improving the warning message. Can you review #442?

> which must be “Fr-Sa 18:00-06:00; PH Sa-Su 00:00-06:00; PH Mo-Fr off”

I still like my shorter example better. Do you see anything wrong with that? See also #442

**Comment by fabi003** [comment]
Now I saw, that even my “fixed” example 4 is wrong, as it is possible that the day before the PH on Sunday is also a PH, for example 25.12. and 26.12. so an additional rule like “; PH -1 day PH off” is needed, but according to the spec this is not defined. Evaluation website throws no error, but it also didn't work for a test rule (as expected).

So example 4 should now be “Fr-Sa 18:00-06:00; PH Sa-Su 00:00-06:00; PH Mo-Fr off; PH -1 day PH off"

**Comment by ypid** [comment]
Whats wrong with [Fr-Sa 18:00-06:00; PH 18:00-06:00 off](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Fr-Sa%2018%3A00-06%3A00%3B%20PH%2018%3A00-06%3A00%20off&lat=50.7390213&lon=7.1064796&mode=0&DATE=1684363200000)?

I think you have the wrong understanding of what `PH 18:00-06:00 off` is doing.

**Comment by fabi003** [comment]
Thanks! I hadn't the idea to write this as an explicit closing time rule.

**Comment by fabi003** [comment]
The explanation text looks OK to me.

**Comment by fabi003** [comment]
Is there any reason, why e.g. “Fr-Sa 15:00-18:00; Sa 18:00-20:00” overwrites the whole Saturday, but your above closing time rule “Fr-Sa 18:00-06:00; PH 18:00-06:00 off” overwrites only the time span affected (bug?)? Should the rule not be “Fr-Sa 18:00-06:00, PH 18:00-06:00 off” (additional rule + last rule wins)? Because off the all-day overwriting, I hadn't the idea with the explicit closing time first.

**Comment by ypid** [comment]
Thanks! See the specification why it works: https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:rule_modifier:closed
