### ISSUE TITLE
11:11-13:22; Mo-Fr 10:00-16:00 open, 12:00-12:30 off

### ISSUE THREAD

**Issue by grinapo** [opening-hours/opening_hours.js#53]
Isn't "," should keep the day so off should only apply to Mo-Fr?

**Comment by ypid** [comment]
> I also don‘t know a better one …

Actually I do now and it is quite obvious …

"&&" would be perfect as [\<additional_rule_separator\>](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#additional_rule_separator).
