### ISSUE TITLE
Missing public holidays for Sweden

### ISSUE THREAD

**Issue by VorpalBlade** [opening-hours/opening_hours.js#72]
The tool told me the following when I was verifying a conditional maxspeed in Sweden:
> An error occurred during evaluation of the value "PH". Please file a bug report here: https://github.com/ypid/opening_hours.js/issues?state=open. No holidays are defined for country se. You can also add them: https://github.com/ypid/opening_hours.js

The official law for public holidays is http://www.riksdagen.se/sv/Dokument-Lagar/Lagar/Svenskforfattningssamling/Lag-1989253-om-allmanna-hel_sfs-1989-253/ (in Swedish)

The English Wikipedia has the following page that may be of help (though it appears to be incomplete, it doesn't specify when Easter actually is for example): https://en.wikipedia.org/wiki/Public_holidays_in_Sweden

For that reason here is a translation of the law (I'm a native speaker):
```
1 § Public holiday means in law or other constitutional writing:

Sundays, including Easter day and Pentecost, New Year's Day, Epiphany, May Day, Christmas Day and Boxing Day, even when they do not fall on a Sunday,
Long Friday, Easter Monday, Ascension Day, National Day, Midsummer Day and All Saints Day.

Law (2004:1320)

2 § The in 1 § listed holidays occurs:

New Year's day           January 1
Epiphany                 January 6
Long Friday              The Friday preceding Easter Sunday
Easter day               Sunday immediately following the full moon
                         which falls on or immediately following March 21
Easter Monday            The day after Easter Sunday
Ascension                Sixth Thursday after Easter Sunday
Pentecost                The seventh Sunday after Easter Sunday
National Day             June 6
Midsummer Day            On Saturday that falls during the period
                         between June 20 and June 26
All Saints Day           On Saturday that falls during the period
                         between 31 October and November 6
Christmas Day            December 25
Boxing Day               26th December.

Law (2004:1320)
```

**Comment by ypid** [comment]
Thanks very much for the translation. I will probably add them in release [](https://github.com/ypid/opening_hours.js/milestones/v3.1.1

**Comment by VorpalBlade** [comment]
Though looking at the relevant source file, I now see that you want the holiday names to use the localized values. Since the ordering of the entries matches, you could probably easily pick those from the Swedish law text though?

**Comment by ypid** [comment]
I guess localized holiday names make more sense. I will use the Swedish onces from the law text.

**Comment by ypid** [comment]
Swedish public holidays seem to have some special cases like "On Saturday that falls during the period between June 20 and June 26". Because of that, I would like to wait until #71 is closed before I will implement them.

**Comment by ypid** [comment]
Can you maybe submit a PR please? See https://github.com/ypid/opening_hours.js#holidays-1

**Comment by ypid** [comment]
This issue is not dependent on #71 anymore. PR are still welcome.

**Comment by VorpalBlade** [comment]
Alas I'm not a JavaScript programmer, so a PR might not be a good idea. My day job is as an embedded real time systems C/C++ programmer.

**Comment by ypid** [comment]
@VorpalBlade Thanks for your help!

**Comment by ypid** [comment]
@VorpalBlade Can you have a look if the definition is correct and works correctly? If all works as expected you can close this issue.

URL for testing: http://openingh.openstreetmap.de/evaluation_tool/?EXP=PH&DATE=1466965680000&lat=63&lon=16&mode=0/

PH for the next 4 years:

```
./PH_SH_exporter.js --verbose --from=2016 --to=2020 --public-holidays --country se --region _se /tmp/se_PH.txt
2015-12-31 nyårsdagen
2016-01-05 trettondedag jul
2016-03-24 långfredagen
2016-03-26 påskdagen
2016-03-27 annandag påsk
2016-04-30 första maj
2016-05-14 pingstdagen
2016-06-05 nationaldagen
2016-06-24 midsommardagen
2016-11-04 alla helgons dag
2016-12-24 juldagen
2016-12-25 annandag jul
2016-12-31 nyårsdagen
2017-01-05 trettondedag jul
2017-04-13 långfredagen
2017-04-15 påskdagen
2017-04-16 annandag påsk
2017-04-30 första maj
2017-06-03 pingstdagen
2017-06-05 nationaldagen
2017-06-23 midsommardagen
2017-11-03 alla helgons dag
2017-12-24 juldagen
2017-12-25 annandag jul
2017-12-31 nyårsdagen
2018-01-05 trettondedag jul
2018-03-29 långfredagen
2018-03-31 påskdagen
2018-04-01 annandag påsk
2018-04-30 första maj
2018-05-19 pingstdagen
2018-06-05 nationaldagen
2018-06-22 midsommardagen
2018-11-02 alla helgons dag
2018-12-24 juldagen
2018-12-25 annandag jul
2018-12-31 nyårsdagen
2019-01-05 trettondedag jul
2019-04-18 långfredagen
2019-04-20 påskdagen
2019-04-21 annandag påsk
2019-04-30 första maj
2019-06-05 nationaldagen
2019-06-08 pingstdagen
2019-06-21 midsommardagen
2019-11-01 alla helgons dag
2019-12-24 juldagen
2019-12-25 annandag jul
2019-12-31 nyårsdagen
2020-01-05 trettondedag jul
2020-04-09 långfredagen
2020-04-11 påskdagen
2020-04-12 annandag påsk
2020-04-30 första maj
2020-05-30 pingstdagen
2020-06-05 nationaldagen
2020-06-19 midsommardagen
2020-10-30 alla helgons dag
2020-12-24 juldagen
2020-12-25 annandag jul
```

**Comment by ypid** [comment]
Closing. Feel free to comment.

**Comment by squeak9** [comment]
Can this be opened again now that there's a pull request?

**Comment by ypid** [comment]
Opening this issue does not help and is against the policy that I have documented here: https://github.com/opening-hours/opening_hours.js?tab=readme-ov-file#holiday-data

I mainly need help in form of PR reviews and testing. See #341
