### ISSUE TITLE
Jul-Sep SH

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#79]

**Comment by dex2000** [comment]
Mhh, grad drüber gestolpert: http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Su%2015%3A00-20%3A00%3B%20Jul-Sep%20SH%20off&DATE=1437657840000&lat=48.7769&lon=9.1844&mode=0

    Die Einrichtung hat jetzt geöffnet

Wird das nicht unterstützt, oder wo is mein Denkfehler? Siehe auch: http://forum.openstreetmap.org/viewtopic.php?id=53060

**Comment by ypid** [comment]
Hi

So wie es aussieht funktioniert `Jul-Sep SH` jetzt auch im Browser [so wie es soll](https://github.com/opening-hours/opening_hours.js/commit/1ce3ea6956840e6cf5e2f4761f0f2a7a036bd3a8#diff-1dd241c4cd3fd1dd89c570cee98b79ddR1082)

Wo „zickt“ den der Validator rum :wink: ?

**Comment by dex2000** [comment]
Siehe mein Link oben. Ich hab als aktuelles Datum 23.Juli eingestellt, der Validator meint aber es wäre offen.

**Comment by dex2000** [comment]
arr, nehme alles zurück ... herrjeminee

**Comment by ypid** [comment]
@dex2000 Müsste alles passen mit SH, oder? Dann würde ich das Ticket noch schließen können für die 3.4.0 Version.

**Comment by dex2000** [comment]
Jo, mach zu, mir is nix aufgefallen und meine Anfrage war mal wieder das schöne Brett.

**Comment by ypid** [comment]
Alles klar. Ein Ticket weniger offen :wink:
